// This file is auto-generated by schema-to-types
// Do not edit manually - run 'npm run generate-types' to regenerate

// Generated types based on SimpleSchema definitions

export interface Member {
	_id: string
	firstName: string
	lastName: string
	fullName?: string
	initials?: string
	number: number
	code?: string
	phone?: string
	email?: string
	createdAt?: Date
}

export interface Theme {
	_id: string
	title?: string
	question?: string
	quarter?: string
	organizations?: any[]
	topOrgsManual?: any[]
	numTopOrgs?: number
	chitWeight?: unknown
	matchRatio?: unknown
	consolationAmount?: number
	consolationActive?: boolean
	leverageTotal?: number
	saves?: any[]
	presentationSettings?: unknown
	slug?: string
	messagesStatus?: any[]
	createdAt?: Date
}

export interface ChitVote {
	_id: string
	voteSource?: "kiosk" | "mobile"
	createdAt?: Date
}

export interface MatchPledge {
	_id: string
	member?: unknown
	anonymous?: boolean
	notes?: string
	createdAt?: Date
}

export interface Organization {
	_id: string
	title?: string
	ask?: number
	description?: string
	image?: unknown
	chitVotes?: unknown
	defaultValue?: unknown
	amountFromVotes?: number
	topOff?: number
	pledges?: any[]
	leverageFunds?: number
	createdAt?: Date
}

export interface Allocation {
	_id: string
	voteSource?: "kiosk" | "mobile"
	createdAt?: Date
}

export interface MemberTheme {
	_id: string
	chits?: number
	amount?: number
	chitVotes?: any[]
	allocations?: any[]
	createdAt?: Date
}

export interface Rounds {
	_id: string
}

export interface Message {
	_id: string
	subject?: string
	body?: string
	type: "text" | "email"
	active?: boolean
	order?: number
	includeLink?: boolean
	optOutRounds?: unknown
	defaultValue?: unknown
	createdAt?: Date
	updatedAt?: Date
}

export interface PresentationSettings {
	_id: string
	currentPage?: string
	timerLength?: unknown
	animateOrgs?: boolean
	leverageVisible?: boolean
	savesVisible?: boolean
	colorizeOrgs?: boolean
	chitVotingActive?: boolean
	fundsVotingActive?: boolean
	topupsActive?: boolean
	resultsOffset?: number
	useKioskChitVoting?: boolean
	useKioskFundsVoting?: boolean
	resultsVisited?: boolean
	awardsPresentation?: boolean
	awardAmount?: number
	topupEmailConfirm?: boolean
	showAskOnOrgCards?: boolean
	twilioRateLimit?: number
}

