// This file is auto-generated by schema-to-types
// Do not edit manually - run 'npm run generate-types' to regenerate

// Generated types based on SimpleSchema definitions

export interface Member {
	_id: string
	firstName: string
	lastName: string
	fullName?: string
	initials?: string
	number: number
	code?: string
	phone?: string
	email?: string
	createdAt?: Date
}

export interface OrgSave {
	_id: string
	org?: string
	amount?: number
	name?: string
}

export interface MessageStatus {
	_id: string
	messageId?: string
	sending?: boolean
	sent?: boolean
	error?: boolean
}

export interface Theme {
	_id: string
	title?: string
	question?: string
	quarter?: string
	organizations?: string[]
	topOrgsManual?: string[]
	numTopOrgs?: number
	chitWeight?: number
	matchRatio?: number
	consolationAmount?: number
	consolationActive?: boolean
	leverageTotal?: number
	saves?: OrgSave[]
	presentationSettings?: string
	slug?: string
	messagesStatus?: MessageStatus[]
	createdAt?: Date
}

export interface OrgChitVoteSummary {
	weight?: number
	count?: number
}

export interface MatchPledge {
	_id: string
	amount: number
	member?: string
	anonymous?: boolean
	notes?: string
	createdAt?: Date
}

export interface Organization {
	_id: string
	title?: string
	theme?: string
	ask?: number
	description?: string
	image?: string
	chitVotes?: OrgChitVoteSummary
	amountFromVotes?: number
	topOff?: number
	pledges?: MatchPledge[]
	leverageFunds?: number
	createdAt?: Date
}

export interface Allocation {
	_id: string
	organization?: string
	amount?: number
	voteSource?: "kiosk" | "mobile"
	createdAt?: Date
}

export interface ChitVote {
	_id: string
	organization?: string
	votes?: number
	voteSource?: "kiosk" | "mobile"
	createdAt?: Date
}

export interface MemberTheme {
	_id: string
	theme?: string
	member?: string
	chits?: number
	amount?: number
	chitVotes?: ChitVote[]
	allocations?: Allocation[]
	createdAt?: Date
}

export interface Rounds {
	_id: string
	one?: boolean
	two?: boolean
}

export interface Message {
	_id: string
	title?: string
	subject?: string
	body?: string
	type: "text" | "email"
	active?: boolean
	order?: number
	includeLink?: boolean
	optOutRounds?: Rounds
	createdAt?: Date
	updatedAt?: Date
}

export interface PresentationSettings {
	_id: string
	currentPage?: string
	timerLength?: number
	animateOrgs?: boolean
	leverageVisible?: boolean
	savesVisible?: boolean
	colorizeOrgs?: boolean
	chitVotingActive?: boolean
	fundsVotingActive?: boolean
	topupsActive?: boolean
	resultsOffset?: number
	useKioskChitVoting?: boolean
	useKioskFundsVoting?: boolean
	resultsVisited?: boolean
	awardsPresentation?: boolean
	awardAmount?: number
	topupEmailConfirm?: boolean
	showAskOnOrgCards?: boolean
	twilioRateLimit?: number
}

